### ISSUE TITLE
Get rid of Bootstrap warning

### ISSUE THREAD

**Issue by talk2bryan** [talk2bryan/UofMeme#168]
The warning that states that `Bootstrap::VERSION` had already been initialized is annoying and needs to go ASAP

**Comment by talk2bryan** [comment]
@AifuwaRoland pls create a pull request to master for this fix thx :100:

**Comment by AifuwaRoland** [comment]
heres the link to fix this warning https://github.com/talk2bryan/UofMeme/wiki/Common-Bugs-and-their-fixes
