### ISSUE TITLE
Wiki unfinished - Code Review

### ISSUE THREAD

**Issue by talk2bryan** [talk2bryan/UofMeme#80]
Need to add information on how to properly review a new feature
- How to test changes locally

**Comment by AifuwaRoland** [comment]
- We need to show devs how to run new features in a dev environment as prod.

**Comment by talk2bryan** [comment]
I have made the suggested edit to this document. https://github.com/talk2bryan/UofMeme/wiki/Commit-and-Code-Review-Standards
 This is now completed
